[package]
name = "prime-time"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
primes = "0.3.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"

[profile.release]
lto = true
strip = true
